data:
  image: tianon/true
  container_name: powerdns_data
  volumes:
    - /var/named

server:
  image: oriaks/powerdns_server
  container_name: powerdns_server
  log_driver: syslog
  ports:
    - "0.0.0.0:53:53/tcp"
    - "0.0.0.0:53:53/udp"
  restart: always
  volumes_from:
    - data
